version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:18

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Build
          command: npm run build
          working_directory: client

      - persist_to_workspace:
          root: .
          paths:
            - client/dist

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build