version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:18.19

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm install
          working_directory: client

      - run:
          name: Build
          command: npm run test
          working_directory: client

  build:
    docker:
      - image: cimg/node:18.19

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm install
          working_directory: client

      - run:
          name: Build
          command: npm run build
          working_directory: client

      - persist_to_workspace:
          root: .
          paths:
            - client/dist
  
  deploy:
    docker:
      - image: cimg/aws:2024.03
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy to AWS S3
          command: |
            aws s3 sync client/dist s3://static-website-franeksz --delete

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build
